### ISSUE TITLE
dismissWithClickedButtonIndex will crash when push app to background.

### ISSUE THREAD

**Issue by kenneth1106** [arashpayan/appirater#269] opened 2017-11-16 14:50 UTC
when displaying the rating view with iOS version lower then 10.3 and push app to background, will crash at 
[self.ratingAlert dismissWithClickedButtonIndex:-1 animated:NO];
with the exception 
[UIAlertController dismissWithClickedButtonIndex:animated:]: unrecognized selector sent to instance 0x1658f000

**Comment by jamescahall** [comment] 2017-11-16 21:34
This is a duplicate of https://github.com/arashpayan/appirater/issues/266

**Closed** 2017-11-17 07:04 UTC
